package com.smart.restaurant_saas.rbac.contract;

import static org.assertj.core.api.Assertions.assertThat;

import com.smart.restaurant_saas.rbac.contract.PermissionGateScanner.Gate;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.json.JsonMapper;

/**
 * Regenerates {@code docs/contracts/permission-manifest.json} — the contract the admin-web screen
 * map is authored against. See docs/RBAC_UI_CONTRACT_PLAN.md.
 *
 * <p>The manifest is a generated file: edit the controllers, not the JSON.
 */
class PermissionManifestTest {

    private static final Path MANIFEST = Path.of("docs/contracts/permission-manifest.json");

    @Test
    void everyPreAuthorizeExpressionIsUnderstood() {
        List<Gate> unparseable = PermissionGateScanner.scan().stream().filter(Gate::unparseable).toList();

        assertThat(unparseable)
                .describedAs("""
                        A @PreAuthorize expression is in a shape the manifest generator does not \
                        understand, so the frontend contract would silently omit it. Either write \
                        the gate in an existing shape, or teach PermissionGateScanner the new one \
                        — do not delete this assertion.""")
                .extracting(Gate::handler, Gate::expression)
                .isEmpty();
    }

    @Test
    void writeManifest() throws IOException {
        List<Gate> gates = PermissionGateScanner.scan();

        // Refuse to overwrite a good manifest with one that is missing a gate we failed to read.
        assertThat(gates).filteredOn(Gate::unparseable)
                .describedAs("manifest not regenerated — fix the unparseable gate first")
                .isEmpty();

        Map<String, List<Map<String, String>>> byPermission = new TreeMap<>();
        Map<String, List<Map<String, String>>> byRoleRule = new TreeMap<>();
        List<Map<String, String>> authenticatedOnly = new ArrayList<>();

        for (Gate gate : gates) {
            if (gate.unparseable()) {
                continue;
            }
            Map<String, String> endpoint = endpointOf(gate);
            gate.permissionCodes().forEach(code ->
                    byPermission.computeIfAbsent(code, unused -> new ArrayList<>()).add(endpoint));
            gate.roleRules().forEach(rule ->
                    byRoleRule.computeIfAbsent(rule, unused -> new ArrayList<>()).add(endpoint));
            if (gate.permissionCodes().isEmpty() && gate.roleRules().isEmpty()) {
                authenticatedOnly.add(endpoint);
            }
        }

        Map<String, Object> manifest = new LinkedHashMap<>();
        manifest.put("$comment", "Generated by PermissionManifestTest. Do not edit by hand.");
        manifest.put("permissions", toEntries(byPermission, "code"));
        manifest.put("roleGates", toEntries(byRoleRule, "rule"));
        manifest.put("authenticatedOnly", authenticatedOnly);

        Files.createDirectories(MANIFEST.getParent());
        Files.writeString(MANIFEST, JsonMapper.builder().build()
                .writerWithDefaultPrettyPrinter()
                .writeValueAsString(manifest) + "\n");

        assertThat(byPermission).describedAs("no permission gates found — the scanner is broken").isNotEmpty();
    }

    private static List<Map<String, Object>> toEntries(Map<String, List<Map<String, String>>> source, String keyName) {
        List<Map<String, Object>> entries = new ArrayList<>();
        source.forEach((key, endpoints) -> {
            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put(keyName, key);
            entry.put("endpoints", endpoints);
            entries.add(entry);
        });
        return entries;
    }

    private static Map<String, String> endpointOf(Gate gate) {
        Map<String, String> endpoint = new LinkedHashMap<>();
        endpoint.put("method", gate.httpMethod());
        endpoint.put("path", gate.path());
        endpoint.put("handler", gate.handler());
        return endpoint;
    }
}
