-- Supports D19-D27: final-only POS-completed orders, immutable frozen order lines,
-- and one-way online/aggregator intake linking before POS completion.

CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    order_type VARCHAR(30) NOT NULL,
    order_source VARCHAR(30) NOT NULL,
    aggregator_name VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    cancellation_stage VARCHAR(40),
    payment_method VARCHAR(30) NOT NULL,
    table_no VARCHAR(255),
    branch_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    total_amount NUMERIC(18,2) NOT NULL,
    order_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    external_order_reference VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_orders_type CHECK (order_type IN ('DINE_IN', 'TAKEAWAY', 'DELIVERY')),
    CONSTRAINT chk_orders_source CHECK (order_source IN ('POS', 'ONLINE', 'AGGREGATOR')),
    CONSTRAINT chk_orders_status CHECK (status IN ('COMPLETE', 'CANCELLED')),
    CONSTRAINT chk_orders_cancellation_stage CHECK (
        cancellation_stage IS NULL
        OR cancellation_stage IN ('BEFORE_KITCHEN', 'IN_KITCHEN_COOKED', 'IN_KITCHEN_NOT_COOKED', 'AFTER_DONE')
    ),
    CONSTRAINT chk_orders_payment_method CHECK (payment_method IN ('CASH', 'CARD', 'WALLET', 'AGGREGATOR')),
    CONSTRAINT chk_orders_total_amount CHECK (total_amount >= 0),
    CONSTRAINT chk_orders_table_no_type CHECK (order_type = 'DINE_IN' OR table_no IS NULL),
    CONSTRAINT chk_orders_cancellation_stage_status CHECK (
        (status = 'CANCELLED' AND cancellation_stage IS NOT NULL)
        OR (status = 'COMPLETE' AND cancellation_stage IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.order_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    quantity NUMERIC(18,6) NOT NULL,
    unit_price NUMERIC(18,2) NOT NULL,
    line_total NUMERIC(18,2) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_order_line_quantity CHECK (quantity > 0),
    CONSTRAINT chk_order_line_unit_price CHECK (unit_price >= 0),
    CONSTRAINT chk_order_line_total CHECK (line_total >= 0)
);

CREATE TABLE IF NOT EXISTS public.incoming_order_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    source VARCHAR(30) NOT NULL,
    aggregator_name VARCHAR(255),
    external_reference_id VARCHAR(255),
    branch_id BIGINT,
    payload JSONB NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    completed_order_id BIGINT,
    sent_to_pos_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_incoming_order_request_source CHECK (source IN ('ONLINE', 'AGGREGATOR')),
    CONSTRAINT chk_incoming_order_request_status CHECK (status IN ('RECEIVED', 'SENT_TO_POS', 'LINKED')),
    CONSTRAINT chk_incoming_order_request_completed_link CHECK (
        (status = 'LINKED' AND completed_order_id IS NOT NULL)
        OR (status <> 'LINKED')
    )
);

CREATE INDEX IF NOT EXISTS idx_orders_tenant_id
    ON public.orders (tenant_id);
CREATE INDEX IF NOT EXISTS idx_orders_branch_id
    ON public.orders (branch_id);
CREATE INDEX IF NOT EXISTS idx_orders_tenant_branch_date
    ON public.orders (tenant_id, branch_id, order_date);
CREATE INDEX IF NOT EXISTS idx_orders_tenant_status
    ON public.orders (tenant_id, status);

CREATE INDEX IF NOT EXISTS idx_order_line_tenant_order
    ON public.order_line (tenant_id, order_id);
CREATE INDEX IF NOT EXISTS idx_order_line_tenant_recipe
    ON public.order_line (tenant_id, recipe_id);

CREATE INDEX IF NOT EXISTS idx_incoming_order_request_tenant_status
    ON public.incoming_order_request (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_incoming_order_request_tenant_completed_order
    ON public.incoming_order_request (tenant_id, completed_order_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_orders_tenant') THEN
        ALTER TABLE public.orders
            ADD CONSTRAINT fk_orders_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_orders_branch') THEN
        ALTER TABLE public.orders
            ADD CONSTRAINT fk_orders_branch
            FOREIGN KEY (branch_id) REFERENCES public.branches(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_orders_warehouse') THEN
        ALTER TABLE public.orders
            ADD CONSTRAINT fk_orders_warehouse
            FOREIGN KEY (warehouse_id) REFERENCES public.warehouse(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_line_tenant') THEN
        ALTER TABLE public.order_line
            ADD CONSTRAINT fk_order_line_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_line_order') THEN
        ALTER TABLE public.order_line
            ADD CONSTRAINT fk_order_line_order
            FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_line_product') THEN
        ALTER TABLE public.order_line
            ADD CONSTRAINT fk_order_line_product
            FOREIGN KEY (product_id) REFERENCES public.product(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_line_recipe') THEN
        ALTER TABLE public.order_line
            ADD CONSTRAINT fk_order_line_recipe
            FOREIGN KEY (recipe_id) REFERENCES public.recipe(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_incoming_order_request_tenant') THEN
        ALTER TABLE public.incoming_order_request
            ADD CONSTRAINT fk_incoming_order_request_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_incoming_order_request_branch') THEN
        ALTER TABLE public.incoming_order_request
            ADD CONSTRAINT fk_incoming_order_request_branch
            FOREIGN KEY (branch_id) REFERENCES public.branches(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_incoming_order_request_completed_order') THEN
        ALTER TABLE public.incoming_order_request
            ADD CONSTRAINT fk_incoming_order_request_completed_order
            FOREIGN KEY (completed_order_id) REFERENCES public.orders(id);
    END IF;
END $$;

-- Supports POS device registration and branch resolution.

CREATE TABLE IF NOT EXISTS public.device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    branch_id BIGINT NOT NULL,
    secret_key_hash VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE INDEX IF NOT EXISTS idx_device_branch_id
    ON public.device (branch_id);
CREATE INDEX IF NOT EXISTS idx_device_tenant_id
    ON public.device (tenant_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_device_secret_key_hash') THEN
        ALTER TABLE public.device
            ADD CONSTRAINT uk_device_secret_key_hash
            UNIQUE (secret_key_hash);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_device_tenant') THEN
        ALTER TABLE public.device
            ADD CONSTRAINT fk_device_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_device_branch') THEN
        ALTER TABLE public.device
            ADD CONSTRAINT fk_device_branch
            FOREIGN KEY (branch_id) REFERENCES public.branches(id);
    END IF;
END $$;

