-- Supports D28-D31 and D42-D45: interim order consumption docs with direct recalculate.

CREATE TABLE IF NOT EXISTS public.order_consumption (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    error_details JSONB,
    processed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_order_consumption_status
        CHECK (status IN ('PENDING', 'IN_PROGRESS', 'POSTED', 'CONFLICT'))
);

CREATE TABLE IF NOT EXISTS public.order_consumption_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id BIGINT NOT NULL,
    order_line_id BIGINT NOT NULL,
    is_consumed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_order_consumption_pending_per_wh
    ON public.order_consumption (tenant_id, warehouse_id)
    WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS idx_order_consumption_tenant_status
    ON public.order_consumption (tenant_id, status);

CREATE INDEX IF NOT EXISTS idx_order_consumption_line_doc
    ON public.order_consumption_line (doc_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_order_consumption_line_order_line
    ON public.order_consumption_line (order_line_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_consumption_tenant') THEN
        ALTER TABLE public.order_consumption
            ADD CONSTRAINT fk_order_consumption_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_consumption_warehouse') THEN
        ALTER TABLE public.order_consumption
            ADD CONSTRAINT fk_order_consumption_warehouse
            FOREIGN KEY (warehouse_id) REFERENCES public.warehouse(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_consumption_line_doc') THEN
        ALTER TABLE public.order_consumption_line
            ADD CONSTRAINT fk_order_consumption_line_doc
            FOREIGN KEY (doc_id) REFERENCES public.order_consumption(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_consumption_line_order_line') THEN
        ALTER TABLE public.order_consumption_line
            ADD CONSTRAINT fk_order_consumption_line_order_line
            FOREIGN KEY (order_line_id) REFERENCES public.order_line(id);
    END IF;
END $$;
