-- =====================================================================
-- Fixed Assets module (D46-D51): asset headers, per-purchase-batch lines,
-- disposal events, and maintenance cost records, plus the ASSETS_MANAGE
-- RBAC permission seed.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    name_ar VARCHAR(255),
    category VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_asset_category CHECK (category IN
        ('FURNITURE', 'KITCHEN_EQUIPMENT', 'FINISHING', 'ELECTRONICS', 'OTHER')),
    CONSTRAINT chk_asset_status CHECK (status IN
        ('ACTIVE', 'PARTIALLY_DISPOSED', 'FULLY_DISPOSED'))
);

CREATE TABLE IF NOT EXISTS public.asset_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    label VARCHAR(255),
    quantity NUMERIC(18,6) NOT NULL,
    remaining_quantity NUMERIC(18,6) NOT NULL,
    unit_cost NUMERIC(18,6) NOT NULL,
    total_cost NUMERIC(18,6) NOT NULL,
    purchase_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_asset_line_status CHECK (status IN
        ('ACTIVE', 'PARTIALLY_DISPOSED', 'FULLY_DISPOSED')),
    CONSTRAINT chk_asset_line_quantity CHECK (quantity > 0),
    CONSTRAINT chk_asset_line_remaining CHECK (remaining_quantity >= 0 AND remaining_quantity <= quantity),
    CONSTRAINT chk_asset_line_unit_cost CHECK (unit_cost >= 0),
    CONSTRAINT chk_asset_line_total_cost CHECK (total_cost >= 0)
);

CREATE TABLE IF NOT EXISTS public.asset_disposal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    asset_line_id BIGINT NOT NULL,
    quantity_disposed NUMERIC(18,6) NOT NULL,
    reason VARCHAR(30) NOT NULL,
    disposal_date DATE NOT NULL,
    notes VARCHAR(1000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_asset_disposal_reason CHECK (reason IN
        ('DAMAGED', 'LOST', 'OBSOLETE', 'SOLD')),
    CONSTRAINT chk_asset_disposal_quantity CHECK (quantity_disposed > 0)
);

CREATE TABLE IF NOT EXISTS public.asset_maintenance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    asset_line_id BIGINT NOT NULL,
    cost NUMERIC(18,6) NOT NULL,
    maintenance_date DATE NOT NULL,
    description VARCHAR(1000),
    vendor VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_asset_maintenance_cost CHECK (cost >= 0)
);

-- Indexes on every FK column plus the required line/child lookups.
CREATE INDEX IF NOT EXISTS idx_asset_tenant ON public.asset (tenant_id);
CREATE INDEX IF NOT EXISTS idx_asset_branch_id ON public.asset (branch_id);
CREATE INDEX IF NOT EXISTS idx_asset_line_tenant ON public.asset_line (tenant_id);
CREATE INDEX IF NOT EXISTS idx_asset_line_asset_id ON public.asset_line (asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_disposal_tenant ON public.asset_disposal (tenant_id);
CREATE INDEX IF NOT EXISTS idx_asset_disposal_asset_id ON public.asset_disposal (asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_disposal_asset_line_id ON public.asset_disposal (asset_line_id);
CREATE INDEX IF NOT EXISTS idx_asset_maintenance_tenant ON public.asset_maintenance (tenant_id);
CREATE INDEX IF NOT EXISTS idx_asset_maintenance_asset_id ON public.asset_maintenance (asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_maintenance_asset_line_id ON public.asset_maintenance (asset_line_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asset_tenant') THEN
        ALTER TABLE public.asset
            ADD CONSTRAINT fk_asset_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asset_branch') THEN
        ALTER TABLE public.asset
            ADD CONSTRAINT fk_asset_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asset_line_tenant') THEN
        ALTER TABLE public.asset_line
            ADD CONSTRAINT fk_asset_line_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asset_line_asset') THEN
        ALTER TABLE public.asset_line
            ADD CONSTRAINT fk_asset_line_asset FOREIGN KEY (asset_id) REFERENCES public.asset(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asset_disposal_tenant') THEN
        ALTER TABLE public.asset_disposal
            ADD CONSTRAINT fk_asset_disposal_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asset_disposal_asset') THEN
        ALTER TABLE public.asset_disposal
            ADD CONSTRAINT fk_asset_disposal_asset FOREIGN KEY (asset_id) REFERENCES public.asset(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asset_disposal_line') THEN
        ALTER TABLE public.asset_disposal
            ADD CONSTRAINT fk_asset_disposal_line FOREIGN KEY (asset_line_id) REFERENCES public.asset_line(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asset_maintenance_tenant') THEN
        ALTER TABLE public.asset_maintenance
            ADD CONSTRAINT fk_asset_maintenance_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asset_maintenance_asset') THEN
        ALTER TABLE public.asset_maintenance
            ADD CONSTRAINT fk_asset_maintenance_asset FOREIGN KEY (asset_id) REFERENCES public.asset(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_asset_maintenance_line') THEN
        ALTER TABLE public.asset_maintenance
            ADD CONSTRAINT fk_asset_maintenance_line FOREIGN KEY (asset_line_id) REFERENCES public.asset_line(id);
    END IF;
END $$;

-- RBAC: single ASSETS_MANAGE permission (all asset read/write endpoints guard on it).
INSERT INTO permissions (code, module, name, description, type)
VALUES
    ('ASSETS_MANAGE', 'ASSETS', 'Manage Assets',
     'View and manage fixed assets, lines, disposals, and maintenance.', 'ACTION')
ON CONFLICT (code) DO UPDATE
SET module = EXCLUDED.module,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    type = EXCLUDED.type,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO role_permissions (role_id, permission_id, created_at)
SELECT r.id, p.id, CURRENT_TIMESTAMP
FROM roles r
JOIN permissions p ON p.code = 'ASSETS_MANAGE'
WHERE r.code IN ('OWNER', 'SYS_ADMIN')
ON CONFLICT (role_id, permission_id) DO NOTHING;
