-- V1 menu foundations: tenant menu categories, products, and direct product recipes.
-- Supports D13 by intentionally omitting a separate menu/multi-menu abstraction.

CREATE TABLE IF NOT EXISTS public.menu_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_menu_category_sort_order CHECK (sort_order >= 0)
);

CREATE TABLE IF NOT EXISTS public.product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    selling_price NUMERIC(18,2) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    menu_category_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_product_selling_price CHECK (selling_price >= 0)
);

CREATE TABLE IF NOT EXISTS public.recipe_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    quantity NUMERIC(18,6) NOT NULL,
    uom_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT uk_recipe_item_tenant_product_material
        UNIQUE (tenant_id, product_id, material_id),
    CONSTRAINT chk_recipe_item_quantity CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_menu_category_tenant_sort
    ON public.menu_category (tenant_id, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_product_tenant_category
    ON public.product (tenant_id, menu_category_id);
CREATE INDEX IF NOT EXISTS idx_product_tenant_name
    ON public.product (tenant_id, name);
CREATE INDEX IF NOT EXISTS idx_recipe_item_tenant_product
    ON public.recipe_item (tenant_id, product_id);
CREATE INDEX IF NOT EXISTS idx_recipe_item_material
    ON public.recipe_item (material_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_menu_category_tenant') THEN
        ALTER TABLE public.menu_category
            ADD CONSTRAINT fk_menu_category_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_product_tenant') THEN
        ALTER TABLE public.product
            ADD CONSTRAINT fk_product_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_product_menu_category') THEN
        ALTER TABLE public.product
            ADD CONSTRAINT fk_product_menu_category
            FOREIGN KEY (menu_category_id) REFERENCES public.menu_category(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_recipe_item_tenant') THEN
        ALTER TABLE public.recipe_item
            ADD CONSTRAINT fk_recipe_item_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_recipe_item_product') THEN
        ALTER TABLE public.recipe_item
            ADD CONSTRAINT fk_recipe_item_product
            FOREIGN KEY (product_id) REFERENCES public.product(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_recipe_item_material') THEN
        ALTER TABLE public.recipe_item
            ADD CONSTRAINT fk_recipe_item_material
            FOREIGN KEY (material_id) REFERENCES public.material(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_recipe_item_uom') THEN
        ALTER TABLE public.recipe_item
            ADD CONSTRAINT fk_recipe_item_uom
            FOREIGN KEY (uom_id) REFERENCES public.uom(id);
    END IF;
END $$;
