ALTER TABLE uom
    ADD COLUMN IF NOT EXISTS name_ar VARCHAR(255);

ALTER TABLE material_category
    ADD COLUMN IF NOT EXISTS name_ar VARCHAR(255);

ALTER TABLE material_catalog
    ADD COLUMN IF NOT EXISTS name_ar VARCHAR(255);

ALTER TABLE material
    ADD COLUMN IF NOT EXISTS name_ar VARCHAR(255);

ALTER TABLE warehouse
    ADD COLUMN IF NOT EXISTS name_ar VARCHAR(255);

ALTER TABLE supplier
    ADD COLUMN IF NOT EXISTS name_ar VARCHAR(255);
