-- Supports immutable recipe version history by introducing recipe headers and
-- moving recipe items from product-level ownership to recipe-version ownership.

CREATE TABLE IF NOT EXISTS public.recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE INDEX IF NOT EXISTS idx_recipe_tenant_product
    ON public.recipe (tenant_id, product_id);
CREATE INDEX IF NOT EXISTS idx_recipe_tenant_product_active
    ON public.recipe (tenant_id, product_id, is_active);

ALTER TABLE public.recipe_item
    ADD COLUMN IF NOT EXISTS recipe_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_recipe_item_tenant_recipe
    ON public.recipe_item (tenant_id, recipe_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_recipe_tenant') THEN
        ALTER TABLE public.recipe
            ADD CONSTRAINT fk_recipe_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_recipe_product') THEN
        ALTER TABLE public.recipe
            ADD CONSTRAINT fk_recipe_product
            FOREIGN KEY (product_id) REFERENCES public.product(id) ON DELETE CASCADE;
    END IF;
END $$;

INSERT INTO public.recipe (
    tenant_id,
    product_id,
    is_active,
    created_at,
    updated_at,
    created_by,
    updated_by
)
SELECT
    recipe_rows.tenant_id,
    recipe_rows.product_id,
    TRUE,
    recipe_rows.created_at,
    recipe_rows.updated_at,
    recipe_rows.created_by,
    recipe_rows.updated_by
FROM (
    SELECT
        ri.tenant_id,
        ri.product_id,
        MIN(ri.created_at) AS created_at,
        MAX(ri.updated_at) AS updated_at,
        MIN(ri.created_by) AS created_by,
        MAX(ri.updated_by) AS updated_by
    FROM public.recipe_item ri
    WHERE ri.product_id IS NOT NULL
    GROUP BY ri.tenant_id, ri.product_id
) recipe_rows
LEFT JOIN public.recipe existing_recipe
    ON existing_recipe.tenant_id = recipe_rows.tenant_id
   AND existing_recipe.product_id = recipe_rows.product_id
WHERE existing_recipe.id IS NULL;

UPDATE public.recipe_item ri
SET recipe_id = r.id
FROM public.recipe r
WHERE ri.recipe_id IS NULL
  AND ri.tenant_id = r.tenant_id
  AND ri.product_id = r.product_id;

ALTER TABLE public.recipe_item
    ALTER COLUMN recipe_id SET NOT NULL;

ALTER TABLE public.recipe_item
    DROP CONSTRAINT IF EXISTS uk_recipe_item_tenant_product_material;
ALTER TABLE public.recipe_item
    DROP CONSTRAINT IF EXISTS fk_recipe_item_product;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_recipe_item_tenant_recipe_material') THEN
        ALTER TABLE public.recipe_item
            ADD CONSTRAINT uk_recipe_item_tenant_recipe_material
            UNIQUE (tenant_id, recipe_id, material_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_recipe_item_recipe') THEN
        ALTER TABLE public.recipe_item
            ADD CONSTRAINT fk_recipe_item_recipe
            FOREIGN KEY (recipe_id) REFERENCES public.recipe(id) ON DELETE CASCADE;
    END IF;
END $$;

DROP INDEX IF EXISTS idx_recipe_item_tenant_product;

ALTER TABLE public.recipe_item
    DROP COLUMN IF EXISTS product_id;
