-- =====================================================================
-- Loyalty V1: tenant customer capture for the POS.
-- Adds the customer table (unique per tenant+phone), a nullable orders.customer_id
-- FK link, and the LOYALTY_VIEW / LOYALTY_MANAGE RBAC permissions + role grants.
-- Scope is deliberately minimal: no points, tiers, offers, or contact details.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE INDEX IF NOT EXISTS idx_customer_tenant ON public.customer (tenant_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_customer_tenant_phone') THEN
        ALTER TABLE public.customer
            ADD CONSTRAINT uk_customer_tenant_phone UNIQUE (tenant_id, phone);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_customer_tenant') THEN
        ALTER TABLE public.customer
            ADD CONSTRAINT fk_customer_tenant FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
END $$;

-- Nullable link from an order to its (optional) loyalty customer. Walk-in orders leave it null.
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON public.orders (customer_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_orders_customer') THEN
        ALTER TABLE public.orders
            ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES public.customer(id);
    END IF;
END $$;

-- RBAC: read/write split mirroring the assets D52 pattern.
-- LOYALTY_VIEW guards GET /api/loyalty/customers; LOYALTY_MANAGE guards the find-or-create POST.
INSERT INTO permissions (code, module, name, description, type)
VALUES
    ('LOYALTY_VIEW', 'LOYALTY', 'View Customers',
     'View the tenant loyalty customer list.', 'ACTION'),
    ('LOYALTY_MANAGE', 'LOYALTY', 'Manage Customers',
     'Create or resolve loyalty customers (POS new-customer capture).', 'ACTION')
ON CONFLICT (code) DO UPDATE
SET module = EXCLUDED.module,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    type = EXCLUDED.type,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;

-- Default grants: owners/admins plus the POS-facing roles that capture customers.
INSERT INTO role_permissions (role_id, permission_id, created_at)
SELECT r.id, p.id, CURRENT_TIMESTAMP
FROM roles r
JOIN permissions p ON p.code IN ('LOYALTY_VIEW', 'LOYALTY_MANAGE')
WHERE r.code IN ('OWNER', 'SYS_ADMIN', 'BRANCH_MANAGER', 'CASHIER')
ON CONFLICT (role_id, permission_id) DO NOTHING;
