-- =====================================================================
-- Restaurant Table master data and TABLES_VIEW / TABLES_MANAGE RBAC.
-- Tables are branch-scoped; table_no is unique within (tenant, branch).
-- Active flag follows the soft-delete pattern used by Branch and Warehouse.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.restaurant_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    table_no VARCHAR(50) NOT NULL,
    capacity INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_restaurant_table_capacity CHECK (capacity >= 1)
);

CREATE INDEX IF NOT EXISTS idx_restaurant_table_tenant
    ON public.restaurant_table (tenant_id);
CREATE INDEX IF NOT EXISTS idx_restaurant_table_tenant_branch
    ON public.restaurant_table (tenant_id, branch_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_restaurant_table_tenant_branch_no') THEN
        ALTER TABLE public.restaurant_table
            ADD CONSTRAINT uk_restaurant_table_tenant_branch_no
            UNIQUE (tenant_id, branch_id, table_no);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_restaurant_table_tenant') THEN
        ALTER TABLE public.restaurant_table
            ADD CONSTRAINT fk_restaurant_table_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_restaurant_table_branch') THEN
        ALTER TABLE public.restaurant_table
            ADD CONSTRAINT fk_restaurant_table_branch
            FOREIGN KEY (branch_id) REFERENCES public.branches(id);
    END IF;
END $$;

-- RBAC: view/manage split following the pattern established by LOYALTY_VIEW/LOYALTY_MANAGE in V18.
INSERT INTO permissions (code, module, name, description, type)
VALUES
    ('TABLES_VIEW',   'TABLES', 'View Tables',   'View restaurant tables.',          'ACTION'),
    ('TABLES_MANAGE', 'TABLES', 'Manage Tables', 'Create, update, and deactivate restaurant tables.', 'ACTION')
ON CONFLICT (code) DO UPDATE
SET module      = EXCLUDED.module,
    name        = EXCLUDED.name,
    description = EXCLUDED.description,
    type        = EXCLUDED.type,
    is_active   = TRUE,
    updated_at  = CURRENT_TIMESTAMP;

-- Grants: owners/admins full access; branch managers and cashiers get view access.
INSERT INTO role_permissions (role_id, permission_id, created_at)
SELECT r.id, p.id, CURRENT_TIMESTAMP
FROM roles r
JOIN permissions p ON p.code IN ('TABLES_VIEW', 'TABLES_MANAGE')
WHERE r.code IN ('OWNER', 'SYS_ADMIN')
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id, created_at)
SELECT r.id, p.id, CURRENT_TIMESTAMP
FROM roles r
JOIN permissions p ON p.code = 'TABLES_VIEW'
WHERE r.code IN ('BRANCH_MANAGER', 'CASHIER')
ON CONFLICT (role_id, permission_id) DO NOTHING;
