-- =====================================================================
-- Cashier POS shift: open/close lifecycle, cash drawer tracking.
-- Status is OPEN | CLOSED (string column, no partial index needed since
-- the OPEN uniqueness is enforced at the application layer).
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.shift (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT NOT NULL,
    branch_id             BIGINT NOT NULL,
    cashier_user_id       BIGINT NOT NULL,
    opened_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    closed_at             TIMESTAMP WITHOUT TIME ZONE,
    opening_cash          NUMERIC(18,6) NOT NULL,
    closing_cash_counted  NUMERIC(18,6),
    status                VARCHAR(10) NOT NULL DEFAULT 'OPEN',
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    created_by            BIGINT,
    updated_by            BIGINT,
    CONSTRAINT chk_shift_status
        CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT chk_shift_opening_cash
        CHECK (opening_cash >= 0),
    CONSTRAINT chk_shift_closing_cash
        CHECK (closing_cash_counted IS NULL OR closing_cash_counted >= 0),
    CONSTRAINT chk_shift_closed_at
        CHECK (
            (status = 'CLOSED' AND closed_at IS NOT NULL AND closing_cash_counted IS NOT NULL)
            OR status = 'OPEN'
        )
);

CREATE INDEX IF NOT EXISTS idx_shift_tenant_id
    ON public.shift (tenant_id);
CREATE INDEX IF NOT EXISTS idx_shift_tenant_cashier_status
    ON public.shift (tenant_id, cashier_user_id, status);
CREATE INDEX IF NOT EXISTS idx_shift_branch_id
    ON public.shift (branch_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shift_tenant') THEN
        ALTER TABLE public.shift
            ADD CONSTRAINT fk_shift_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shift_branch') THEN
        ALTER TABLE public.shift
            ADD CONSTRAINT fk_shift_branch
            FOREIGN KEY (branch_id) REFERENCES public.branches(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shift_cashier_user') THEN
        ALTER TABLE public.shift
            ADD CONSTRAINT fk_shift_cashier_user
            FOREIGN KEY (cashier_user_id) REFERENCES public.users(id);
    END IF;
END $$;
