-- Product variants + add-ons (D13): variant grouping via a self-referencing parent,
-- menu visibility flag, bilingual variant labels/descriptions, and a plain product-to-product
-- add-on suggestion link table. Parenthood stays derived (no is_parent column) — a product is a
-- parent iff another product references it via parent_product_id.

-- Additive product columns (all nullable/defaulted; existing rows unaffected).
ALTER TABLE public.product
    ADD COLUMN IF NOT EXISTS parent_product_id BIGINT;
ALTER TABLE public.product
    ADD COLUMN IF NOT EXISTS variant_label VARCHAR(255);
ALTER TABLE public.product
    ADD COLUMN IF NOT EXISTS variant_label_ar VARCHAR(255);
ALTER TABLE public.product
    ADD COLUMN IF NOT EXISTS is_menu BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public.product
    ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.product
    ADD COLUMN IF NOT EXISTS description_ar TEXT;

CREATE INDEX IF NOT EXISTS idx_product_parent_product_id
    ON public.product (parent_product_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_product_parent') THEN
        ALTER TABLE public.product
            ADD CONSTRAINT fk_product_parent
            FOREIGN KEY (parent_product_id) REFERENCES public.product(id);
    END IF;
    -- Belt-and-suspenders with the service guard: a variant child can never be a menu item.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_product_variant_not_menu') THEN
        ALTER TABLE public.product
            ADD CONSTRAINT chk_product_variant_not_menu
            CHECK (parent_product_id IS NULL OR is_menu = FALSE);
    END IF;
END $$;

-- Add-on suggestion links: a host product references another tenant product as a suggested add-on.
-- Menu-side only — no runtime ordering/consumption effect.
CREATE TABLE IF NOT EXISTS public.product_add_on (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    add_on_product_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT uk_product_add_on UNIQUE (tenant_id, product_id, add_on_product_id),
    CONSTRAINT chk_product_add_on_not_self CHECK (product_id <> add_on_product_id)
);

CREATE INDEX IF NOT EXISTS idx_product_add_on_product_id
    ON public.product_add_on (product_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_product_add_on_tenant') THEN
        ALTER TABLE public.product_add_on
            ADD CONSTRAINT fk_product_add_on_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_product_add_on_product') THEN
        ALTER TABLE public.product_add_on
            ADD CONSTRAINT fk_product_add_on_product
            FOREIGN KEY (product_id) REFERENCES public.product(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_product_add_on_add_on_product') THEN
        ALTER TABLE public.product_add_on
            ADD CONSTRAINT fk_product_add_on_add_on_product
            FOREIGN KEY (add_on_product_id) REFERENCES public.product(id) ON DELETE CASCADE;
    END IF;
END $$;
