-- Supports D55/D56 table sections: sections become branch-owned master data,
-- and restaurant_table stores a nullable section FK instead of a free-text section.

CREATE TABLE IF NOT EXISTS public.table_section (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    name_ar VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_table_section_branch FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);

CREATE INDEX IF NOT EXISTS idx_table_section_branch_id
    ON public.table_section (branch_id);

ALTER TABLE public.restaurant_table
    ADD COLUMN IF NOT EXISTS section_id BIGINT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'restaurant_table'
          AND column_name = 'section'
    ) THEN
        INSERT INTO public.table_section (tenant_id, branch_id, name, is_active, created_at)
        SELECT DISTINCT rt.tenant_id, rt.branch_id, rt.section, TRUE, CURRENT_TIMESTAMP
        FROM public.restaurant_table rt
        WHERE rt.section IS NOT NULL
          AND btrim(rt.section) <> ''
          AND NOT EXISTS (
              SELECT 1
              FROM public.table_section ts
              WHERE ts.tenant_id = rt.tenant_id
                AND ts.branch_id = rt.branch_id
                AND ts.name = rt.section
          );

        UPDATE public.restaurant_table rt
        SET section_id = ts.id
        FROM public.table_section ts
        WHERE rt.section_id IS NULL
          AND rt.section IS NOT NULL
          AND ts.tenant_id = rt.tenant_id
          AND ts.branch_id = rt.branch_id
          AND ts.name = rt.section;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_restaurant_table_section'
    ) THEN
        ALTER TABLE public.restaurant_table
            ADD CONSTRAINT fk_restaurant_table_section
            FOREIGN KEY (section_id) REFERENCES public.table_section(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_restaurant_table_section_id
    ON public.restaurant_table (section_id);

DROP INDEX IF EXISTS public.idx_restaurant_table_tenant_branch_section;

CREATE INDEX IF NOT EXISTS idx_restaurant_table_tenant_branch_section_id
    ON public.restaurant_table (tenant_id, branch_id, section_id);

ALTER TABLE public.restaurant_table
    DROP COLUMN IF EXISTS section;
