-- Replaces the per-line is_consumed flag and the doc-level error_details JSON with one persisted
-- row per (doc, material) — the grain consumption actually executes at (D29 step 3, D94).
--
-- A line requires several materials, so a line-level flag cannot record the outcome of a run in
-- which one of its materials consumed and another did not. The line then reads as outstanding and
-- OrderConsumptionAvailabilityService subtracts the already-consumed material a second time.
--
-- UOM layers (D87/D88): required_quantity and available_quantity are DISPLAY UOM (layer 2) —
-- the layer stock_balance.quantity and stock_batch.quantity live in, which is what availability
-- subtracts from and what the screen renders. entered_quantity is the recipe item's own UOM,
-- the raw entered layer InventoryLedgerService.record() converts to stock UOM (D3); it is kept
-- so recalculate can rebuild the ledger command without re-aggregating.
-- Every quantity column has its unit alongside it.

CREATE TABLE IF NOT EXISTS public.order_consumption_material (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    required_quantity NUMERIC(18, 6) NOT NULL,
    required_uom_id BIGINT NOT NULL,
    entered_quantity NUMERIC(18, 6) NOT NULL,
    entered_uom_id BIGINT NOT NULL,
    is_consumed BOOLEAN NOT NULL DEFAULT FALSE,
    available_quantity NUMERIC(18, 6),
    failure_reason VARCHAR(20),
    exception_class VARCHAR(255),
    exception_message TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT chk_order_consumption_material_failure_reason
        CHECK (failure_reason IN ('INSUFFICIENT_STOCK', 'TECHNICAL_FAILURE')),
    CONSTRAINT chk_order_consumption_material_consumed_clean
        CHECK (NOT is_consumed
               OR (failure_reason IS NULL AND exception_class IS NULL AND exception_message IS NULL)),
    CONSTRAINT chk_order_consumption_material_insufficient_has_available
        CHECK (failure_reason IS DISTINCT FROM 'INSUFFICIENT_STOCK' OR available_quantity IS NOT NULL),
    CONSTRAINT chk_order_consumption_material_technical_has_class
        CHECK (failure_reason IS DISTINCT FROM 'TECHNICAL_FAILURE' OR exception_class IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_order_consumption_material_doc_material
    ON public.order_consumption_material (doc_id, material_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_consumption_material_doc') THEN
        ALTER TABLE public.order_consumption_material
            ADD CONSTRAINT fk_order_consumption_material_doc
            FOREIGN KEY (doc_id) REFERENCES public.order_consumption(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_consumption_material_material') THEN
        ALTER TABLE public.order_consumption_material
            ADD CONSTRAINT fk_order_consumption_material_material
            FOREIGN KEY (material_id) REFERENCES public.material(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_consumption_material_required_uom') THEN
        ALTER TABLE public.order_consumption_material
            ADD CONSTRAINT fk_order_consumption_material_required_uom
            FOREIGN KEY (required_uom_id) REFERENCES public.uom(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_order_consumption_material_entered_uom') THEN
        ALTER TABLE public.order_consumption_material
            ADD CONSTRAINT fk_order_consumption_material_entered_uom
            FOREIGN KEY (entered_uom_id) REFERENCES public.uom(id);
    END IF;
END $$;

-- The outcome now lives on order_consumption_material. No data migration: existing consumption
-- documents are development data.
ALTER TABLE public.order_consumption_line
    DROP COLUMN IF EXISTS is_consumed;

ALTER TABLE public.order_consumption
    DROP COLUMN IF EXISTS error_details;
