-- Supports rotating, server-revocable refresh tokens for authenticated sessions.

CREATE TABLE IF NOT EXISTS public.refresh_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    device_id   BIGINT,
    token_hash  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked_at  TIMESTAMP WITHOUT TIME ZONE,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  BIGINT,
    updated_by  BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_refresh_token_hash
    ON public.refresh_token (token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user_active
    ON public.refresh_token (user_id) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_refresh_token_device_active
    ON public.refresh_token (device_id) WHERE device_id IS NOT NULL AND revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_refresh_token_expires_at
    ON public.refresh_token (expires_at);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_refresh_token_tenant') THEN
        ALTER TABLE public.refresh_token
            ADD CONSTRAINT fk_refresh_token_tenant
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_refresh_token_user') THEN
        ALTER TABLE public.refresh_token
            ADD CONSTRAINT fk_refresh_token_user
            FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_refresh_token_device') THEN
        ALTER TABLE public.refresh_token
            ADD CONSTRAINT fk_refresh_token_device
            FOREIGN KEY (device_id) REFERENCES public.device(id) ON DELETE CASCADE;
    END IF;
END $$;
