-- =====================================================================
-- D119-D123: the shift is anchored to the device, not the cashier.
--
-- V22 keyed the shift on cashier_user_id and stated that open-shift
-- uniqueness was "enforced at the application layer". Both are reversed
-- here: the device is the drawer (D119) and uniqueness is a partial
-- unique index (D120).
--
-- WHY THE OLD ROWS ARE ARCHIVED RATHER THAN MIGRATED IN PLACE
--
-- device_id is NOT NULL and carries the entire variance chain: each
-- shift's handoverVariance is measured against the previous closed shift
-- ON THE SAME DEVICE (D121). Legacy rows record no device and none can be
-- recovered -- the branch holding most of them has five devices, and the
-- concept did not exist when the rows were written. Any backfill would be
-- a guess, and a guessed device does not merely mislabel one row: it
-- inserts a fabricated predecessor into the chain, so the first real shift
-- on that device would be handed a handoverVariance computed against
-- invented data. D121 calls that out specifically -- the handover figure
-- is the strongest signal the module produces precisely because the drawer
-- sat closed, and it is worthless if its baseline is fiction.
--
-- Nothing is deleted. Every legacy row keeps every column and audit field
-- in shift_legacy, and the orders that referenced them keep that link in
-- shift_legacy_order. The new table starts empty, so the first shift on
-- every device is genuinely its first (null handoverVariance, D121).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Archive the legacy table.
--
-- Postgres does not rename a table's indexes or its identity sequence
-- along with the table, and both share a schema-wide namespace -- so the
-- new table's shift_pkey and shift_id_seq would collide with the old
-- ones. Renaming them is required, not cosmetic.
-- ---------------------------------------------------------------------
ALTER TABLE IF EXISTS public.shift RENAME TO shift_legacy;

ALTER SEQUENCE IF EXISTS public.shift_id_seq RENAME TO shift_legacy_id_seq;
ALTER INDEX IF EXISTS public.shift_pkey RENAME TO shift_legacy_pkey;
ALTER INDEX IF EXISTS public.idx_shift_tenant_id RENAME TO idx_shift_legacy_tenant_id;
ALTER INDEX IF EXISTS public.idx_shift_tenant_cashier_status
    RENAME TO idx_shift_legacy_tenant_cashier_status;
ALTER INDEX IF EXISTS public.idx_shift_branch_id RENAME TO idx_shift_legacy_branch_id;

COMMENT ON TABLE public.shift_legacy IS
    'Pre-D119 cashier-keyed shifts. Read-only history; no device, so not migrated into shift.';

-- ---------------------------------------------------------------------
-- 2. Preserve the order -> legacy shift links before orders.shift_id is
--    cleared. The direction is one-to-many, so it cannot be reconstructed
--    from shift_legacy alone once the column is nulled.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.shift_legacy_order (
    order_id BIGINT NOT NULL,
    shift_id BIGINT NOT NULL,
    CONSTRAINT pk_shift_legacy_order PRIMARY KEY (order_id)
);

INSERT INTO public.shift_legacy_order (order_id, shift_id)
SELECT id, shift_id
FROM public.orders
WHERE shift_id IS NOT NULL
ON CONFLICT (order_id) DO NOTHING;

COMMENT ON TABLE public.shift_legacy_order IS
    'orders.shift_id as it stood before the D119 rewrite, pointing at shift_legacy.id.';

-- ---------------------------------------------------------------------
-- 3. The new shift.
-- ---------------------------------------------------------------------
CREATE TABLE public.shift (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT NOT NULL,

    -- The drawer. Branch is reached through the device and deliberately
    -- not stored again -- a second copy goes stale (D119).
    device_id           BIGINT NOT NULL,

    -- A real column, fixed at open, never derived from opened_at at read
    -- time: a shift opening at 22:00 and closing at 03:00 belongs entirely
    -- to the earlier day (D120).
    business_date       DATE NOT NULL,

    opened_by_user_id   BIGINT NOT NULL,
    closed_by_user_id   BIGINT,

    -- Derived from closed_by <> opened_by, never accepted from the client.
    -- chk_shift_forced_close below makes that a database invariant rather
    -- than a service convention (D122).
    forced_close        BOOLEAN NOT NULL DEFAULT FALSE,

    opening_count       NUMERIC(18,6) NOT NULL,
    closing_count       NUMERIC(18,6),

    -- Null on a device's first shift, never zero. A zero here is a
    -- fabricated finding (D121).
    handover_variance   NUMERIC(18,6),

    -- Stored at close, never returned to a POS caller (D123).
    expected_cash       NUMERIC(18,6),
    variance            NUMERIC(18,6),
    expenses_at_close   NUMERIC(18,6),

    status              VARCHAR(10) NOT NULL DEFAULT 'OPEN',
    opened_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    closed_at           TIMESTAMP WITHOUT TIME ZONE,

    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          BIGINT,
    updated_by          BIGINT,

    CONSTRAINT chk_shift_status
        CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT chk_shift_opening_count
        CHECK (opening_count >= 0),
    CONSTRAINT chk_shift_closing_count
        CHECK (closing_count IS NULL OR closing_count >= 0),

    -- Strict in both directions. An OPEN shift holds no close figures at
    -- all, so there is no expected figure in the row for a read path to
    -- leak before the count is taken (D123); a CLOSED shift holds the
    -- complete set.
    CONSTRAINT chk_shift_close_fields CHECK (
        (status = 'OPEN'
             AND closed_at IS NULL
             AND closed_by_user_id IS NULL
             AND closing_count IS NULL
             AND expected_cash IS NULL
             AND variance IS NULL
             AND expenses_at_close IS NULL
             AND forced_close = FALSE)
        OR
        (status = 'CLOSED'
             AND closed_at IS NOT NULL
             AND closed_by_user_id IS NOT NULL
             AND closing_count IS NOT NULL
             AND expected_cash IS NOT NULL
             AND variance IS NOT NULL
             AND expenses_at_close IS NOT NULL)
    ),

    CONSTRAINT chk_shift_forced_close CHECK (
        (forced_close = TRUE  AND closed_by_user_id IS NOT NULL
                              AND closed_by_user_id <> opened_by_user_id)
        OR
        (forced_close = FALSE AND (closed_by_user_id IS NULL
                                   OR closed_by_user_id = opened_by_user_id))
    )
);

-- One OPEN shift per device, enforced by the database. V22 explicitly
-- chose application enforcement; that choice is reversed (D120). Two open
-- shifts against one drawer would be two accounts of the same money with
-- no variance attributable to either.
CREATE UNIQUE INDEX IF NOT EXISTS uk_shift_open_per_device
    ON public.shift (device_id)
    WHERE status = 'OPEN';

CREATE INDEX IF NOT EXISTS idx_shift_tenant_business_date
    ON public.shift (tenant_id, business_date);
CREATE INDEX IF NOT EXISTS idx_shift_tenant_status
    ON public.shift (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_shift_device
    ON public.shift (device_id);
CREATE INDEX IF NOT EXISTS idx_shift_opened_by
    ON public.shift (opened_by_user_id);

-- The shifts list sorts by variance by default, not by date (D125): the
-- screen exists to bring the anomalous to the top.
CREATE INDEX IF NOT EXISTS idx_shift_tenant_variance
    ON public.shift (tenant_id, variance);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shift_tenant_new') THEN
        ALTER TABLE public.shift
            ADD CONSTRAINT fk_shift_tenant_new
            FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shift_device') THEN
        ALTER TABLE public.shift
            ADD CONSTRAINT fk_shift_device
            FOREIGN KEY (device_id) REFERENCES public.device(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shift_opened_by_user') THEN
        ALTER TABLE public.shift
            ADD CONSTRAINT fk_shift_opened_by_user
            FOREIGN KEY (opened_by_user_id) REFERENCES public.users(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shift_closed_by_user') THEN
        ALTER TABLE public.shift
            ADD CONSTRAINT fk_shift_closed_by_user
            FOREIGN KEY (closed_by_user_id) REFERENCES public.users(id);
    END IF;
END $$;

-- ---------------------------------------------------------------------
-- 4. Re-point orders.shift_id at the new table.
--
-- The column and its FK stay; only the referenced rows change. Legacy
-- values are cleared because they name shift_legacy ids, and are already
-- preserved in shift_legacy_order above.
-- ---------------------------------------------------------------------
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS fk_orders_shift;

UPDATE public.orders SET shift_id = NULL WHERE shift_id IS NOT NULL;

ALTER TABLE public.orders
    ADD CONSTRAINT fk_orders_shift
    FOREIGN KEY (shift_id) REFERENCES public.shift(id);
