-- MVP tenant operating settings (O40): one typed row per tenant.
-- Preserve today's POS defaults: tax 14%, no service charge, all order types enabled.
-- Rates are percentages (14, not 0.14). Disabling a charge retains its configured rate.
CREATE TABLE IF NOT EXISTS tenant_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    tax_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    tax_rate NUMERIC(10,4) NOT NULL DEFAULT 14,
    tax_on_service_charge BOOLEAN NOT NULL DEFAULT FALSE,
    service_charge_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    service_charge_rate NUMERIC(10,4) NOT NULL DEFAULT 0,
    dine_in_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    takeaway_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    delivery_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT uk_tenant_settings_tenant UNIQUE (tenant_id),
    CONSTRAINT chk_tenant_settings_tax_rate CHECK (tax_rate BETWEEN 0 AND 100),
    CONSTRAINT chk_tenant_settings_service_charge_rate CHECK (service_charge_rate BETWEEN 0 AND 100),
    CONSTRAINT chk_tenant_settings_order_types CHECK (dine_in_enabled OR takeaway_enabled OR delivery_enabled),
    CONSTRAINT fk_tenant_settings_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

-- D101: backfill timestamps in each tenant's timezone, with no server-zone fallback.
INSERT INTO tenant_settings (tenant_id, created_at)
SELECT id, CURRENT_TIMESTAMP AT TIME ZONE timezone FROM tenants
ON CONFLICT (tenant_id) DO NOTHING;

INSERT INTO permissions (code, module, name, name_en, name_ar, description, type, created_at)
VALUES
    ('TENANT_SETTINGS_VIEW', 'TENANT', 'View Tenant Settings', 'View Tenant Settings', 'عرض إعدادات المطعم',
     'Read tenant tax, service charge and enabled order types.', 'ACTION', CURRENT_TIMESTAMP),
    ('TENANT_SETTINGS_MANAGE', 'TENANT', 'Manage Tenant Settings', 'Manage Tenant Settings', 'إدارة إعدادات المطعم',
     'Change tenant tax, service charge and enabled order types.', 'ACTION', CURRENT_TIMESTAMP)
ON CONFLICT (code) DO UPDATE
SET module = EXCLUDED.module, name = EXCLUDED.name, name_en = EXCLUDED.name_en,
    name_ar = EXCLUDED.name_ar, description = EXCLUDED.description,
    type = EXCLUDED.type, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;

INSERT INTO role_permissions (role_id, permission_id, created_at)
SELECT r.id, p.id, CURRENT_TIMESTAMP
FROM roles r CROSS JOIN permissions p
WHERE (r.code = 'OWNER' AND p.code IN ('TENANT_SETTINGS_VIEW', 'TENANT_SETTINGS_MANAGE'))
   OR (r.code IN ('BRANCH_MANAGER', 'CASHIER') AND p.code = 'TENANT_SETTINGS_VIEW')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- D36: existing users have direct permission snapshots, not live role grants.
INSERT INTO user_permissions (tenant_id, user_id, permission_id, created_at)
SELECT u.tenant_id, u.id, p.id, CURRENT_TIMESTAMP
FROM users u JOIN roles r ON r.id = u.role_id CROSS JOIN permissions p
WHERE (r.code = 'OWNER' AND p.code IN ('TENANT_SETTINGS_VIEW', 'TENANT_SETTINGS_MANAGE'))
   OR (r.code IN ('BRANCH_MANAGER', 'CASHIER') AND p.code = 'TENANT_SETTINGS_VIEW')
ON CONFLICT ON CONSTRAINT uk_user_permissions_tenant_user_permission DO NOTHING;
